### ISSUE TITLE
Link of the paper

### ISSUE THREAD

**Issue by ryanxingql** [XLearning-SCU/2022-CVPR-DART#1]
The [original link](http://pengxi.me/wp-content/uploads/2022/03/Learning-with-Twin-Noisy-Labels-for-Visible-Infrared-Person-Re-Identiﬁcation.pdf) is wrong.

The paper link should be: http://pengxi.me/wp-content/uploads/2022/03/Learning-with-Twin-Noisy-Labels-for-Visible-Infrared-Person-Re-Identification.pdf

**Comment by XLearning-SCU** [comment]
同学您好，我已经收到您的消息。                                    ——四川大学机器学习引论

**Comment by mouxingyang** [comment]
> The [original link](http://pengxi.me/wp-content/uploads/2022/03/Learning-with-Twin-Noisy-Labels-for-Visible-Infrared-Person-Re-Identi%EF%AC%81cation.pdf) is wrong.
> 
> The paper link should be: http://pengxi.me/wp-content/uploads/2022/03/Learning-with-Twin-Noisy-Labels-for-Visible-Infrared-Person-Re-Identification.pdf

Thanks for you correction~
