### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by songjunyu** [XLearning-SCU/2022-CVPR-DART#2]
我想知道是否有TP-FP概率分布的代码

**Comment by zhangzhang1524** [comment]
您好，请问您复现过这篇文章吗？我能请教您一些问题吗？

**Comment by zhangzhang1524** [comment]
> 我想知道是否有TP-FP概率分布的代码

您好，请问您复现过这篇文章吗？我能请教您一些问题吗？

**Comment by mouxingyang** [comment]
> 我想知道是否有TP-FP概率分布的代码

Hi, sorry for late reply. We have uploaded the plot code for TP-FN (plot_pair_distribution) in ``util.py".

**Comment by songjunyu** [comment]
> > 我想知道是否有TP-FP概率分布的代码
> 
> Hi, sorry for late reply. We have uploaded the plot code for TP-FN (plot_pair_distribution) in ``util.py".

thank you for your outstanding work and sincere reponse.

**Comment by songjunyu** [comment]
> > 我想知道是否有TP-FP概率分布的代码
> 
> 您好，请问您复现过这篇文章吗？我能请教您一些问题吗？
我并没有复现该论文，然而该论文中的论证方法是我感兴趣的。

**Comment by zhangzhang1524** [comment]
谢谢您的回复，我再自己看看，祝您在科研的道路上越走越远。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XLearning-SCU/2022-CVPR-DART"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月30日(星期四) 晚上8:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XLearning-SCU/2022-CVPR-DART] 可视化 (Issue #2)





   
我想知道是否有TP-FP概率分布的代码
  
您好，请问您复现过这篇文章吗？我能请教您一些问题吗？
 我并没有复现该论文，然而该论文中的论证方法是我感兴趣的。

**Comment by zhangzhang1524** [comment]
> > > 我想知道是否有TP-FP概率分布的代码
> > 
> > 
> > 您好，请问您复现过这篇文章吗？我能请教您一些问题吗？
> > 我并没有复现该论文，然而该论文中的论证方法是我感兴趣的。

谢谢您的回复，我再自己看看，祝您在科研的道路上越走越远。
