### ISSUE TITLE
Acquisition of the noise id

### ISSUE THREAD

**Issue by WheatCao** [XLearning-SCU/2022-CVPR-DART#4]
Hello, I have some doubts about the part of the code that differentiates TN, and whether the use of **rgb_noiseIdx** for differentiation is causing data leakage. By definition, the model should not be able to directly obtain which noise ids are included. I'm not sure if I'm wrong about this variable. Can u give me an answer?
`T = (prob_A_V[evaltrainset.rgb_noiseIdx] < args.p_threshold). sum() / len(evaltrainset.rgb_noiseIdx)
`

**Comment by XLearning-SCU** [comment]
Hi,

We just use the posted code for observing and logging. The statistics of TP, FN, FP and TN could help readers better understand the robustness achieved.

Notably, the rgb_noiseIdx and rgb_cleanIdx would not be used for training and testing. Therefore, it is **impossible** to cause data leakage.

**Comment by WheatCao** [comment]
> 

Thanks for your answer. I'm sorry I misread it.
